spring:
  liquibase:
    change-log: classpath:db\changelog\master-changelog.yml
  datasource:
    url: jdbc:postgresql://localhost:5432/videogames
    username: postgres
    password: password
    name: videogames
  jpa:
    hibernate:
      ddl-auto: none
  main:
    allow-bean-definition-overriding: true
server:
  error:
    include-message: always
    include-stacktrace: never

springdoc:
  swagger-ui:
    path: /videogames-api-ui.html

rabbit:
  queueName: email-queue
  routingKey: game.created
  exchangeName: email-exchange

